[build]
  base = "gitinsuri"   # Correct subfolder path
  publish = "out"      # Or use ".next" if that's the output folder
  command = "npm run build"   # Correct build command for your app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
