# netlify.toml

[build]
# Specify the base directory for the project (optional)
# Uncomment and set if your project resides in a subdirectory
# base = "gitinsuri"

# The directory to deploy (replace "out" with your build output directory)
publish = "out"

# The build command to generate the production build (modify for your project)
command = "npm run build"

[dev]
# Port and framework detection during local development
framework = "next"

[functions]
# Directory for serverless functions
directory = "netlify/functions"

# Functions timeout and memory limits (optional)
node_bundler = "esbuild"

[[redirects]]
# Example redirect rule
from = "/old-route"
to = "/new-route"
status = 301

[[headers]]
# Example custom header
for = "/*"
values = { "X-Frame-Options" = "DENY" }
